name: hrldas
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - affine=2.4.0=py312h06a4308_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=py312h06a4308_2
  - aws-c-auth=0.7.30=hec5e740_0
  - aws-c-cal=0.7.4=hfd43aa1_1
  - aws-c-common=0.9.28=hb9d3cd8_0
  - aws-c-compression=0.2.19=h756ea98_1
  - aws-c-event-stream=0.4.3=h29ce20c_2
  - aws-c-http=0.8.9=h5e77a74_0
  - aws-c-io=0.14.18=h2af50b2_12
  - aws-c-mqtt=0.10.5=h0009854_0
  - aws-c-s3=0.6.5=h45a0e0a_5
  - aws-c-sdkutils=0.1.19=h756ea98_3
  - aws-checksums=0.1.20=h756ea98_0
  - aws-crt-cpp=0.28.2=h6c0439f_6
  - aws-sdk-cpp=1.11.379=hcf9a2ef_10
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - binutils=2.44=h4852527_5
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - blosc=1.21.6=hf7d4471_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hbb29018_2
  - cdsapi=0.7.7=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - cfgrib=0.9.15.1=pyhd8ed1ab_0
  - cfitsio=4.4.1=ha728647_2
  - cftime=1.6.5=py312h4f23490_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=py312h06a4308_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cmake=3.31.1=hf9cb763_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-gcc-specs=14.3.0=he8ccf15_16
  - contourpy=1.3.3=py312hd9148b4_3
  - cycler=0.12.1=pyhcf101f3_2
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - eccodes=2.41.0=h8bb6dbc_0
  - ecmwf-datastores-client=0.4.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - findlibs=0.1.2=pyhd8ed1ab_0
  - fmt=11.0.2=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h8a5da7c_0
  - fortran-compiler=1.11.0=h9bea470_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=hf309648_0
  - gcc=14.3.0=h76bdaa0_7
  - gcc_impl_linux-64=14.3.0=hd9e9e21_7
  - gcc_linux-64=14.3.0=h298d278_17
  - geos=3.12.1=h59595ed_0
  - geotiff=1.7.3=hf7fa9e8_2
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gfortran=14.3.0=he448592_7
  - gfortran_impl_linux-64=14.3.0=h1a219da_16
  - gfortran_linux-64=14.3.0=h9ce9316_17
  - giflib=5.2.2=h5eee18b_0
  - git=2.45.2=pl5321he096aa3_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=9.0.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - jasper=4.2.8=he3c4edf_0
  - json-c=0.17=h1220068_1
  - kealib=1.5.3=hf8d3e68_2
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.7.7=hfab0078_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp18.1=18.1.8=default_h99862b1_17
  - libclang13=21.1.0=default_h746c552_1
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libfabric=2.4.0=ha770c72_1
  - libfabric1=2.4.0=h8f87c3e_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal=3.9.1=h0f26010_1
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.28.0=h26d7fe4_0
  - libgoogle-cloud-storage=2.28.0=ha262f82_0
  - libgrpc=1.62.2=h2d74bed_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkml=1.3.0=h096b73e_7
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm18=18.1.8=default_hddf928d_9
  - libllvm21=21.1.0=hecd9e04_0
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpmix=5.0.8=h4bd6b51_2
  - libpng=1.6.54=h421ea60_0
  - libpq=16.10=h1cdf469_1
  - libprotobuf=4.25.3=he621ea3_0
  - librttopo=1.1.0=h8917695_15
  - libsanitizer=14.3.0=hd08acf3_7
  - libspatialite=5.1.0=h6fbd9c4_7
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libudev1=258.3=h6569c3e_0
  - libudunits2=2.2.28=h40f5838_3
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.4.1=hb9d3cd8_2
  - matplotlib=3.10.8=py312h7900ff3_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - minizip=4.0.3=hf59b114_0
  - mpi=1.0.1=openmpi
  - multiurl=0.3.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h7934f7d_0
  - ncview=2.1.8=h31cb22a_11
  - netcdf-fortran=4.6.1=nompi_h22f9119_108
  - netcdf4=1.7.2=nompi_py312h21d6d8e_101
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numpy=2.4.1=py312h33ff503_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openmpi=5.0.8=h2fe1745_110
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=10.4.0=py312h56024de_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - poppler=24.04.0=hb6cd0d7_0
  - poppler-data=0.4.12=h06a4308_0
  - postgresql=16.10=hd526058_1
  - proj=9.4.1=h54d7996_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.6.1=py312h9211aeb_9
  - pyside6=6.7.2=py312h91f0f75_4
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-eccodes=2.37.0=py312h4f23490_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.7.2=h7d13b96_3
  - rasterio=1.3.10=py312hc022a17_4
  - rdma-core=61.0=h192683f_0
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - rhash=1.4.6=hb9d3cd8_1
  - rioxarray=0.20.0=pyhd8ed1ab_1
  - s2n=1.5.5=h3931f03_0
  - scipy=1.17.0=py312h54fa4ab_1
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd3eb1b0_0
  - spdlog=1.14.1=hed91bc2_1
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64
  - tiledb=2.24.2=h86fa3b2_12
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzcode=2025c=hb03c661_0
  - tzdata=2025c=he532380_0
  - ucc=1.6.0=hb729f83_1
  - ucx=1.19.1=h567e125_0
  - udunits2=2.2.28=h40f5838_3
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uriparser=0.9.8=h451ca9b_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=py312h06a4308_0
  - xarray=2025.12.0=pyhcf101f3_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=hac6953d_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxaw=1.0.16=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxmu=1.2.1=hb9d3cd8_1
  - xorg-libxpm=3.5.17=hb9d3cd8_1
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/lingbo/miniconda3/envs/hrldas
